


--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION--2

UPDATE [SUBJECT] SET sem_end = sem_end - 3 
	WHERE subject_name = 'матанализ'



ROLLBACK--4

SELECT * FROM [SUBJECT]