-- фантом первый, одни и те же выборки разные строки

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE--только здесь работает нормально

BEGIN TRANSACTION
SELECT * FROM OLYMPIAD WHERE olympiad_name = 'физтех математика'

SELECT * FROM OLYMPIAD WHERE olympiad_name = 'физтех математика'
COMMIT

SELECT * FROM OLYMPIAD