--потерянное изменение, первое 2.0
-- все супер

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION

UPDATE [subject] SET sem_end = sem_end + 3  WHERE subject_name = 'матанализ'


COMMIT

SELECT * FROM [SUBJECT] WHERE subject_name = 'матанализ'