--вставл€ютс€ записи, которых не было в начале транзакции


--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE--все хорошо, в остальных плохо

BEGIN TRANSACTION
SELECT * FROM OLYMPIAD WHERE olympiad_name like '%физтех%'


SELECT * FROM OLYMPIAD WHERE olympiad_name like '%физтех%'
COMMIT



DELETE FROM OLYMPIAD where olympiad_id = 7