



--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

SET IDENTITY_INSERT olympiad ON; 

BEGIN TRANSACTION

INSERT INTO OLYMPIAD(olympiad_id, olympiad_name) VALUES(7, 'физтех биология')
COMMIT



SELECT * FROM OLYMPIAD

