--тупик второй

--2
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION

UPDATE [SUBJECT] SET sem_end = 100 WHERE subject_name = 'матанализ'
UPDATE [SUBJECT] SET sem_end = 101 WHERE subject_name = 'аналит'
--4


COMMIT